### ISSUE TITLE
template fields (e.g. for sendMail) stick when they should go away

### ISSUE THREAD

**Issue by dckc** [rchain-community/liquid-democracy#29]
reported by @jimscarver in https://github.com/rchain-community/liquid-democracy/pull/28#issuecomment-724029665

I noticed this too. I think I found a fix... either I didn't deploy it or something. not sure.

**Comment by vb-cs** [comment]
> 
> 
> reported by @jimscarver in [#28 (comment)](https://github.com/rchain-community/liquid-democracy/pull/28#issuecomment-724029665)
> 
> I noticed this too. I think I found a fix... either I didn't deploy it or something. not sure.

What was done to fix it? Does this issue not exist on your branch?

**Comment by dckc** [comment]
I don't remember.

My branch? I'm not sure what you mean by that.

**Comment by jimscarver** [comment]
We have spent a good deal of time tracking this down without luck. It seems like it could be a bug in the https://mithril.js.org/ framework handling the dom when the new fields are assigned.

I've tagged this help wanted...

**Comment by dckc** [comment]
I'm pretty sure it's not a mithril bug; as I say, I think I found and fixed the problem in `participate.js` at some point.

**Comment by vb-cs** [comment]
@dckc If you found and fixed the problem, are you able to commit the fix? Or have you lost the code which fixed it.

**Comment by dckc** [comment]
I don't remember which code fixed it; it might be committed or it might not.

**Comment by vb-cs** [comment]
resolved
