### ISSUE TITLE
independent test of voting start to tally

### ISSUE THREAD

**Issue by jimscarver** [rchain-community/liquid-democracy#48]
add testvote.rho test.sh?

**Comment by jimscarver** [comment]
https://docs.google.com/document/d/1V5k9tDjztEVDYiXJG1-Hpb0rNtVcV22GrsdXb0pDUx8/edit#

video https://drive.google.com/file/d/1JqFY6izBAMtqOd8ldbqa10UCf-a8MuvD/view?usp=sharing

**Comment by dckc** [comment]
fixed in #45
